### ISSUE TITLE
Compile warning.

### ISSUE THREAD

**Issue by hamsternz** [Foundit3923/PackedFilter#1]
When complied with warnings turned on I get a quite a few warning.

Mostly unused variables, but some are data overflows.

I compiled with "gcc -o main main.c -Wall -pedantic -O4"

(ps. looking at this after your post on Reddit).

**Comment by hamsternz** [comment]
e.g. 

main.c:1017:16: warning: comparison with string literal results in unspecified behavior [-Waddress]
 1017 |     if(success == "FAILED"){

**Comment by Foundit3923** [comment]
I will look into this today. A good chunk of the code has been removed and free calls have been added. We will see how many errors this takes care of.

**Comment by hamsternz** [comment]
Code no longer compiles for me:

    main.c:200:10: error: ‘locations’ undeclared (first use in this function)
      200 |     free(locations);
          |          ^~~~~~~~~

**Comment by Foundit3923** [comment]
Sorry bout the wait, family emergency. Compile errors are fixed, compiles and runs on Ubuntu 20.04.01. If fixed on your end I will close out the issue.
