### ISSUE TITLE
Most likely a issue in strncpy() call.

### ISSUE THREAD

**Issue by hamsternz** [Foundit3923/PackedFilter#2]
This code seems broken

    int query_string_len = strlen(query_string);
    strncpy(temp_query, query_string,query_len);   
    temp_query[query_len] = '\0';
    if(strlen(temp_query) > strlen(query_string)) {
        strncpy(temp_query, temp_query, strlen(query_string));
        temp_query[ query_len ] = '\0';
    }

The "strncpy(temp_query, temp_query, strlen(query_string));" does not seem to make sense.

**Comment by Foundit3923** [comment]
Thank you for bringing this to my attention. This error has been resolved by removing the deprecated code in question. I belonged to a previous iteration and is no longer in use.
