### ISSUE TITLE
Writing outside of array bounds

### ISSUE THREAD

**Issue by hamsternz** [Foundit3923/PackedFilter#3]
This array with six entries has 7 initializers.
    
                char query_input[6] = {search_term[ 1 ],
                                           search_term[ 2 ],
                                           search_term[ 3 ],
                                           search_term[ 4 ],
                                           search_term[ 5 ],
                                           search_term[ 6 ],
                                           search_term[ 7 ]};

**Comment by Foundit3923** [comment]
Thank you for pointing this out. This is part of a section of deprecated code that has been removed.
