### ISSUE TITLE
Memory leaks.

### ISSUE THREAD

**Issue by hamsternz** [Foundit3923/PackedFilter#4]
You have many malloc() calls, but no free calls.

    $ grep malloc main.c
        subquery = (char**) malloc(sizeof(char*));
        //char* temp_query = (char *) malloc(sizeof(char));
                        char *beginningbuff = (char *) malloc(sizeof(char));
                        char *endbuff = (char *) malloc(sizeof(char));
                            query = (char *) malloc(sizeof(char));
                                char *check = (char *) malloc(sizeof(char));
            char* t_temp_query = (char*) malloc(sizeof(char*));
                    char *check = (char *) malloc(sizeof(char));
                    char** locations = (char**) malloc(sizeof(char*) * text_len);
        double ret[2];// = (double*) malloc(sizeof(double));
            t_init_term = (char *) malloc(term_len);
            t_init_query = (char *) malloc(query_len);
            //query_64 = (struct DataItem *) malloc(sizeof(struct DataItem));
            char *temp_query = (char *) malloc(query_len);
            rev = (int*) malloc(sizeof(term_len));
        char *expected_return = (char*) malloc(sizeof(char));

    $ grep free main.c
        //free(query_64);

Most of your mallocs are for single characters - that seems very wrong.

**Comment by Foundit3923** [comment]
This code has been removed as deprecated code. In addition all malloc() now have a free call.
